#!/bin/sh
HOSTNAME=$(hostname -s)
PORT="5433"
DIR=$(cd $(dirname $0) ; pwd)

_ggsci_header_footer () {
	local cmd=$1
	echo "
Brocle GoldenGuff Command Interpreter
Version 11.2.1.0.31 20976570 BGGCORE_11.2.1.0.0OBGGP_PLATFORMS_150815.0601
Linux, x64, 64bit (optimized), PostgreSQL on Aug 20 2015 13:04:24

Copyright (C) 1982, 2016, Brocle and/or its affiliates. All rights reserved.



GGSCI ($HOSTNAME) 1> $cmd


GGSCI ($HOSTNAME) 2> " | awk 'NR>1{print PREV} {PREV=$0} END{printf("%s",$0)}'
}

_start_manager () {
	local START_MANAGER="
Manager started.
"
	local START_MANAGER_STARTED="\
MGR is already running.
"

	test -e $DIR/.mgr && \
		_ggsci_header_footer "$START_MANAGER_STARTED" || \
		_ggsci_header_footer "$START_MANAGER"
	touch $DIR/.mgr
}

_stop_manager() {
	local STOP_MANAGER="
Sending STOP request to MANAGER ...
Request processed.
Manager stopped.
"
	local STOP_MANAGER_STOPPED="\
Manager is already stopped.
"
	test -e $DIR/.mgr && \
		_ggsci_header_footer "$STOP_MANAGER" || \
		_ggsci_header_footer "$STOP_MANAGER_STOPPED"
	test -e $DIR/.mgr && rm $DIR/.mgr || true
}

_info_manager () {
	local INFO_MANAGER="
Manager is running (IP port $HOSTNAME.$PORT).
"
	local INFO_MANAGER_DOWN="
Manager is DOWN!
"
        test -e $DIR/.mgr && \
                _ggsci_header_footer "$INFO_MANAGER" || \
                _ggsci_header_footer "$INFO_MANAGER_DOWN"
}

_send_manager_childstatus_debug () {
	local CHILDSTATUS_DEBUG_0="
Sending CHILDSTATUS, request to MANAGER ...

No Child Process Info Available
"
	local CHILDSTATUS_DEBUG_1="
Sending CHILDSTATUS, request to MANAGER ...

Child Process Status - 1 Entries

ID      Group   Process Retry Retry Time          Start Time          Port
---- -------- --------- ----- ------------------- ------------------- ----
   0 RCDCXXXX      9614    22 2016/06/17 22:08:11 2016/06/07 17:21:50 7840
"
	_ggsci_header_footer "$CHILDSTATUS_DEBUG_1"
}

_send_manager_getportinfo_detail () {
	local GETPORTINFO_DETAIL_0="
Sending GETPORTINFO, request to MANAGER ...

Dynamic Port List

Starting Index 0
Entry Port  Error  Process     Assigned             Program
----- ----- ----- ----------   -------------------  -------
   0   8810     0
   1   8811     0
   2   8812     0
   3   8813     0
   4   8814     0
   5   8815     0
   6   8816     0
   7   8817     0
   8   8818     0
   9   8819     0
  10   8820     0
  11   8821     0
  12   8822     0
  13   8823     0
  14   8824     0
  15   8825     0
  16   8826     0
  17   8827     0
  18   8828     0
  19   8829     0
  20   8830     0
  21   8840     0
"
	local GETPORTINFO_DETAIL_1="
Sending GETPORTINFO, request to MANAGER ...

Dynamic Port List

Starting Index 0
Entry Port  Error  Process     Assigned             Program
----- ----- ----- ----------   -------------------  -------
   0   8810     0      30687   2016/06/08 02:43:22  SERVER
   1   8811     0
   2   8812     0
   3   8813     0
   4   8814     0
   5   8815     0
   6   8816     0
   7   8817     0
   8   8818     0
   9   8819     0
  10   8820     0
  11   8821     0
  12   8822     0
  13   8823     0
  14   8824     0
  15   8825     0
  16   8826     0
  17   8827     0
  18   8828     0
  19   8829     0
  20   8830     0
  21   8840     0
"
	_ggsci_header_footer "$GETPORTINFO_DETAIL_0"
}

_send_manager_getportinfo () {
	local GETPORTINFO_0="
Sending GETPORTINFO, request to MANAGER ...

Dynamic Port List

Starting Index 0
"
	local GETPORTINFO_1="
Sending GETPORTINFO, request to MANAGER ...

Dynamic Port List

Starting Index 0
Entry Port  Error  Process     Assigned             Program
----- ----- ----- ----------   -------------------  -------
   0   8810     0      30687   2016/06/08 02:43:22  SERVER
"
	_ggsci_header_footer "$GETPORTINFO_0"
}

_send_manager_getpurgeoldextracts () {
	local GETPURGEOLDEXTRACTS="
Sending GETPURGEOLDEXTRACTS request to MANAGER ...

PurgeOldExtracts Rules
Fileset                              MinHours MaxHours MinFiles MaxFiles UseCP
/brocle/product/ggpg/dirdat/rw*           720        0        1        0   Y
OK
Extract Trails
Filename                        Oldest_Chkpt_Seqno  IsTable  IsVamTwoPhaseCommit
/brocle/product/ggpg/dirdat/rw     9372
"
	_ggsci_header_footer "$GETPURGEOLDEXTRACTS"
}


while read line
do
	case "$line" in
		'INFO MGR'|'INFO MANAGER'|'STATUS MANAGER')
			_info_manager
			;;
		'SEND MANAGER CHILDSTATUS DEBUG')
			_send_manager_childstatus_debug
			;;
		'SEND MANAGER GETPORTINFO DETAIL')
			_send_manager_getportinfo_detail
			;;
		'SEND MANAGER GETPORTINFO')
			_send_manager_getportinfo
			;;
		'SEND MANAGER GETPURGEOLDEXTRACTS')
			_send_manager_getpurgeoldextracts
			;;
		'START MANAGER')
			_start_manager
			;;
		'STOP MANAGER')
			_stop_manager
			;;
		*)
			;;
	esac
done < "${1:-/dev/stdin}"
